### ISSUE TITLE
请教一下有对比学习的地方

### ISSUE THREAD

**Issue by wilzson** [ijcainer/nerco#3]
你好，我在阅读代码的时候在项目中没找到有对比学习的部分，所以想请教一下大概是在哪个文件上包含对比学习？谢谢

**Comment by mmmner** [comment]
感谢关注，对比学习的部分在这里，请查阅。https://github.com/zhzai/nerco/blob/2c25693cb2d4db499ba9a9d3f72e679ee687c046/modeling/models.py#L1900

**Comment by zhzai** [comment]
感谢关注，对比学习的部分在这里，请查阅。
https://github.com/zhzai/nerco/blob/2c25693cb2d4db499ba9a9d3f72e679ee687c046/modeling/models.py#L1900

**Comment by zhzai** [comment]
感谢关注，对比学习的部分在这里，请查阅。
https://github.com/zhzai/nerco/blob/2c25693cb2d4db499ba9a9d3f72e679ee687c046/modeling/models.py#L1900
